### ISSUE TITLE
Error not captured when running G2Loader.py in test mode (-T)

### ISSUE THREAD

**Issue by Lohrax** [Senzing/g2loader#40]
We (Senzing) provide a sample NPI dataset that can be loaded via a demonstration here: https://senzing.com/connections-in-ppp-loan-data/

This data is already formatted and should be easily ingested. If you run this through G2Loader Test (e.g. ./G2Loader.py -f NPI_Orgs_LasVegas.csv/?data_source=NPI_ORGANIZATION,file_format=CSV -T) it will fail on every row because there is a column of ENTITY_TYPE with a value of ORGANIZATION. By default we do not have an Organization entity type, easy enough to create but I think the error should be captured and summarized.  I don't think the data set formatting should be changed, this is a learning opportunity for the customer as long as the error is captured correctly.

**Comment by antaenc** [comment]
G2Loader to be released with 3.2 no longer inspects entity_type as we are moving away from using it.
