### ISSUE TITLE
G2Loader.py Test improvement for Data Source 

### ISSUE THREAD

**Issue by Lohrax** [Senzing/g2loader#41]
If the DATA_SOURCE does exist, I would like to have the results of "Test" mode (e.g ./G2Loader.py -f NPI_Orgs_LasVegas.csv/?DATA_SOURCE=NPI_ORGANIZATION,file=csv -T) return that the data source is needed or will be in created (default mode).

This will help when typos are made, right now if I input records with a data source of CUSTOMER and when I come back another time to add an additional data under that source and run test before, it all looks good. Even though I may have defined the new data set as a source of CUSTOMERS. Now because of a simple typo and G2Loader.py not pointing it out, I have two different data sources even though I really only wanted one.

**Comment by antaenc** [comment]
See #71
