### ISSUE TITLE
at end of run periodically display number of records left in queue

### ISSUE THREAD

**Issue by jbutcher21** [Senzing/g2loader#47]
Can't tell if process stuck of slowing drawing down records left in queue.  

consider ... before calling join
#---------------------------------------
def wait_for_queues(entity_queue, resume_queue):
    waits = 0
    while entity_queue.qsize() or resume_queue.qsize():
        time.sleep(1)
        waits += 1
        if waits >= 10:
            break
        elif entity_queue.qsize() or resume_queue.qsize():
            print(' waiting for %s entity_queue and %s resume_queue records' % (entity_queue.qsize(), resume_queue.qsize()))

    if (entity_queue.qsize() or resume_queue.qsize()):
        print(' warning: queues are not empty!')
        return False
    return True

**Comment by antaenc** [comment]
See #71
